# Generated by Django 4.0 on 2022-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='password',
        ),
    ]
