# Generated by Django 4.0 on 2022-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
